# -*- coding: utf-8 -*-
"""ex-github.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qeSdj2FN32vpfZVQjgrJq0PXjr-XJQhb
"""

class calculadora:
  def __init__(self, primeiro_numero, segundo_numero):
    self.__primeiro_numero = primeiro_numero
    self.__segundo_numero = segundo_numero

  def soma(self):
    return self.__primeiro_numero + self.__segundo_numero

  def multiplicacao(self):
    return self.__primeiro_numero * self.__segundo_numero

  def divisao(self):
    return self.__primeiro_numero / self.__segundo_numero

cal = calculadora(5, 4)

cal.soma()

cal.multiplicacao()

cal.divisao()